### PR TITLE
Fix scripts and var for latest baremaps

### PR DESCRIPTION
**Pull request by RemiDesgrange**
Also remove unnecessary network settings in docker-compose

### CODE REVIEW

**Review by bchapuis — APPROVED** [review]

**Comment by bchapuis** [comment]
Thanks, you should be able to merge it.

**Comment by RemiDesgrange** [comment]
* maybe I'll add default value for env var so that it works "out of the clone" without even touching the `.env` file
* uncomment "by default" the `entrypoint: "entrypoint.sh` here https://github.com/baremaps/openstreetmap-vecto/pull/32/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R52
WDYT ?

**Comment by bchapuis** [comment]
Sure, it's better if it works without making any changes to the repo.@

**Comment by RemiDesgrange** [comment]
Yes you can still `docker-compose exec app <something>` afterward.

**Comment by RemiDesgrange** [comment]
Ok @bchapuis so here is a sum up of what I've done so far:

* remove unnecessary stuff in `Dockerfile`
* launch `entrypoint.sh` by default. 
* Have default value for env var
* parametrized value of baremaps, default latest but can be change via env var.
* You _only_ need to do `git clone && docker-compose up` to have a working env. Everything is configurable via a `docker-compose.overide.yml` or `.env` file.


I'm not using the baremaps docker image because it inherits from alpine. I wanted to add a new build with ubuntu openjdk in baremaps/baremaps but it seems `jib` doesn't support it :-(

**Comment by bchapuis** [comment]
My experience in this area is limited, so are there any reason why you don't use/like alpine images? I think it is possible to configure jib with an [alternative base image](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#maven-2).

**Comment by RemiDesgrange** [comment]
* relying on different version of `libc` for dev and prod lead me to _very_ weird stuff in production  in the past, that was in python maybe the JVM is better on this but since we are using lmdb C dynlib I doubt it :sweat_smile: 
* inheriting from a debian/ubuntu base openjdk would allow us to install gdal or do multistage build more easily. The docker image is heavier (~200Mo vs ~300Mo). 

I think for now being able to switch baremaps version with the `BAREMAPS_VERSION` env var is good enough for this repo.

**Comment by bchapuis** [comment]
Thanks a lot for these explanations and good point regarding the native libraries. I will try to find a way to generate multiple images with jib in the bare maps repository. Do not hesitate to merge the PR.

**Pull request merged**
