### PR TITLE
Add city names

### PR DESCRIPTION
**Pull request by Yahia1018**

### CODE REVIEW

**Comment by Yahia1018** [comment]
It is a first version, not really good, but I would know @bchapuis what do you think about the structure first of all. 

I don't know if we should make one layer for place_city, one for place_town, etc. _**OR**_ like here one for city + town + village (to add) + hamlet (?), _**OR**_ one layer with all place values ?

I have a problem with the key-value "capital"="yes", that doesn't want to work and it considers Bern as a town while this is a city and a capital... It is ok when I separate the layers, I will try in this direction a few moment.

**Review by bchapuis — COMMENTED** [review]
It's a really good start! I noticed that the names of the small villages around lausanne are not displayed? Do you know why?

**Comment by bchapuis** [comment]
> I don't know if we should make one layer for place_city, one for place_town, etc. _**OR**_ like here one for city + town + village (to add) + hamlet (?), _**OR**_ one layer with all place values ?

we can, but for now I would continue with the points layer and the filter in the style.

**Comment by bchapuis** [comment]
> I have a problem with the key-value "capital"="yes", that doesn't want to work and it considers Bern as a town while this is a city and a capital... It is ok when I separate the layers, I will try in this direction a few moment.

No problem, you can create another issue for this case.

**Comment by Yahia1018** [comment]
Thanks ! Yes, I didn't add the villages, I wanted to try with the cities and the towns first of all.

Okay, I'll try to improve all of that.

**Comment by Yahia1018** [comment]
Another try. I really don't know why that doesn't want to work... following OpenStreetMap, I would make a difference between "big" cities (which are capital=4), "middle" cities (capital=6, admin_centre:4=yes, ... for the moment), other cities and towns.

That try don't display anything, except capitals which are in a separated layer this time, but I would keep somewhere the text-size values because I think they are good choices.

**Comment by Yahia1018** [comment]
I splitted the layers as required. I think it's a very good idea because if we don't do that, when we dezoom, for example instead of display Lausanne in the zone around it, it displays Ecublens which is very smaller. Same for the capitals.

**Review by bchapuis — APPROVED** [review]

**Pull request merged**
