### PR TITLE
Waterway tunnel, railway with "spur" service, private highway_service and railway level_crossing

### PR DESCRIPTION
**Pull request by Yahia1018**

### CODE REVIEW

**Comment by Yahia1018** [comment]
I would like to explain my choices. I choosed the same line-width and color of _waterway_ for the _waterway_tunnel_casing_ because it is a continuity of it. About the _waterway_tunnel_ line-width, I decided to inspire me from your _highway_primary_ and _highway_primary_casing_ which have a difference of 4 at zoom level 20 :

highway_primary highway_primary_casing

**Comment by bchapuis** [comment]
Looks good to me.

Notice that the values for the `base`and `stops` properties were chosen by experimenting with different settings. It may be worth to investigate the use of the other related properties and to see wether the `property expressions`mentionned in the warning of the documentation are more appropriate.

https://maplibre.org/maplibre-gl-js-docs/style-spec/other/#function

Can you create another issue for that?

**Review by bchapuis — APPROVED** [review]

**Comment by Yahia1018** [comment]
However, I am not sure to understand what they mean. Expressions like "stop" will vanish in the future ? And so, we should use expressions like "interpolate" or "step" instead of those who will disappear ?

**Comment by bchapuis** [comment]
I don't think they gonna disappear, but it's probably better to replace these expressions with camera expressions.

https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions#camera-expressions

**Comment by Yahia1018** [comment]
Ok, I was not sure. Thanks for the clarification !

**Review by bchapuis — APPROVED** [review]

**Pull request merged**
