### PR TITLE
Add amenity_college labels

### PR DESCRIPTION
**Pull request by Yahia1018**

### CODE REVIEW

**Comment by Yahia1018** [comment]
I show another college than the one in the issue because it is not displayed (_name_ information missing).  The result of the following query (from tileset) has only 1 result for "Chamblandes" : "Temple de Chamblandes".

Capture d’écran 2022-02-14 à 18 19 13
Capture d’écran 2022-02-14 à 18 15 37

amenity_college-labels-final

**Comment by Yahia1018** [comment]
Solution to :

> I show another college than the one in the issue because it is not displayed (_name_ information missing). The result of the following query (from tileset) has only 1 result for "Chamblandes" : "Temple de Chamblandes".

found in first commit of #211.

**Comment by bchapuis** [comment]
I'm not sure to understand your last comment. Is the name information missing in the database or in the vector tiles?

**Comment by Yahia1018** [comment]
We only needed to add osm_relations for amenity. I did this in the mentionned PR, so everything is in order now.

**Comment by bchapuis** [comment]
Thank you for the clarification.

**Pull request merged**
